version: '3'
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=paul.wirion@gmail.com
      - N8N_BASIC_AUTH_PASSWORD=
    volumes:
      - ./data:/home/node/.n8n
      - ./watch-folder:/root/.n8n/local-files
    restart: unless-stopped